version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - docker version
      # - ${aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email}
      - aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 753392824297.dkr.ecr.eu-central-1.amazonaws.com
      - REPO_URI=753392824297.dkr.ecr.eu-central-1.amazonaws.com/alon_exam_ecr_repo
    
  build:
    commands:
    - docker 
    - echo building the docker image...
    - docker build -t $REPO_URI:latest .
  
  post_build:
    commands:
      - echo Pushing docker image
      - docker push $REPO_URI:latest

artifact:
  file: imagedefinition.json
    